### PR TITLE
Fix heading counters and anchor icon presentation. Resolves #1642

### LINKED ISSUE #1642: Missing css definition breaks a header numbering (proposed fix)
When using a header counting feature (header_enum: decimal) a weird behavior is observed.

* Multiple h2 headers have the same number assigned (e.g. "1.1. header2a", "1.1. header2b", etc)
* Level 3 headers are numbered incorrectly ("1.0.1 header3a","1.0.2 header3b" - note the zero digit in the middle).

Confirmed on firefox 83.0 (64 bit) on Linux.

I tracked this down to app-b205e593a30f1cc0054e2e9ed9fc8af3658d8ef4a62b9708c20f204560deefb7.css, which misses the definition of "h1{counter-reset:h2}.header-enum" (accodring to css definitions - body resets h1, h2 resets h3, h3 resets h4 and so on - but nothing resets the h2 counter).

After patching my local css-file with the missing definition, header numbering works as expected.

Could you please verify the problem and fix a css-file permanently ?

### PR DESCRIPTION
**Pull request by benjaminwil**
This pull request was requested in #1643 in order to fix #1642. (I also cherry-picked the first commit from #1643, then spent some time investigating an alternative solution to the anchor CSS presentation.)

To summarize the issues being solved:

- Heading counters were not being reset when `header_enum: true` was set in a page's frontmatter metadata.
- Link anchor icons (:link:) were not appearing in the correct place and were overlapping the heading text on `:hover`.

I also took this opportunity to re-scope `.anchor` related SCSS.

I also ensured that the `.anchor` icons continue to work if `header_enum: false`.

Here is a screenshot that demonstates where `.anchor` icons appear in relation to their heading:

Screenshot from 2021-02-17 22-34-08

The icons appear in the same place on the page's Y axis whether the heading is an `<h1>` or an `<h6>`.

### CODE REVIEW

**Comment by bartkamphorst** [comment]
This is really, really great @benjaminwil ! I understand why you wanted to do this in a separate PR. 👍

**Comment by dometto** [comment]
Thanks again @benjaminwil! This is really great, so much cleaner! There's a merge conflict because of one of the statically compiled files. You could just leave those out and I can do a final precompile before doing the new release.

**Comment by dometto** [comment]
I might do a new release of gollum after merging this, in order to solve https://github.com/gollum/gollum/issues/1672. We can always do another release for forthcoming features (like the button re-labeling). But please let me know if anything forthcoming absolutely needs to be part of the next release!

**Comment by benjaminwil** [comment]
> But please let me know if anything forthcoming absolutely needs to be part of the next release!

No, nothing else should absolutely need to be part of the next release. I am trying to make these changes as isolated as possible. :+1:

> You could just leave those out and I can do a final precompile before doing the new release.

I believe not merging new compilations could break Gollum's frontend for anyone attempting to run off of `master`, so I will re-commit the compiled assets.

I intend to do this later today or tomorrow.

**Comment by benjaminwil** [comment]
I've recompiled the assets. I think this should be good to merge now.

**Comment by dometto** [comment]
Amazing! I'll do a quick gem release of gollum to include your recent updates, and to fix #1672

**Pull request merged**
