### PR TITLE
initial draft solution for (#1624) extracting git credentials from HTT…

### PR DESCRIPTION
**Pull request by pdinc-oss**
…P headers

### CODE REVIEW

**Comment by dometto** [comment]
Thanks for the PR @pdinc-oss. It looks like the actual authentication occurs outside of gollum. Probably your reverse proxy handles authentication, and sets the relevant HTTP headers upon success?

I am wondering whether it would not be better to implement this using a Rack middleware. Here's a minimal example of how that would look (tested, it works):

```ruby
  class Auth
    def initialize(app)
      @app = app
    end
    
    def call(env)
      if env['HTTP_GIT_AUTHOR_NAME'] && env['HTTP_GIT_AUTHOR_EMAIL']
        env['rack.session'] = {} unless env['rack.session']
        env['rack.session']['gollum.author'] = {
          name:  env['HTTP_GIT_AUTHOR_NAME']
          email: env['HTTP_GIT_AUTHOR_EMAIL']
        }
      end
      @app.call(env)
    end
  end
```

and then:


```ruby
  class App < Sinatra::Base
    use Auth # possibly conditional, use Auth if ... ?
    ...
```

This could easily be expanded so as to make the exact conditions under which to set the session variables (e.g. the name of the http headers) dynamic.

Besides being arguably simpler and more of a racky/ruby-y approach, it also has the advantage of disentangling the setting of committer name and email from the question of whether `@auth_editing_override` should be set to true. The user should be able to set the committer info without overriding that.

Let me know if that would be a good solution for you, and if you would still like to contribute a solution of that form.

**Comment by pdinc-oss** [comment]
Honestly, it is a lot to digest, being unfamiliar with the technology stack. My instant thought goes towards usability - How would a systems administrator download Gollum and configure it?

**Comment by dometto** [comment]
>  How would a systems administrator download Gollum and configure it?

By running gollum with `--config` and adding the code I pasted, or suitably altered code (it probably needs minor changes, e.g. wrapping the block in `module Precious`), to `config.rb`. The only thing that couldn't be accomplished in that way would be the `@auth_editing_override` logic. That would still require a PR that would:

1. Implement command line switch for `--enable-authentication` (no need for `MODE` I think)
2. Change [this line](@ https://github.com/gollum/gollum/blob/master/lib/gollum/app.rb#L101) to something like:

```ruby
 @allow_editing = settings.wiki_options[:allow_editing] || (settings.wiki_options[:authentication] && session['gollum.author'])
```

**Comment by pdinc-oss** [comment]
> > How would a systems administrator download Gollum and configure it?
> 
> By running gollum with `--config` and adding the code ...

This is where the issue we were trying to address starts. It is too much to expect of a SA for a common place method of A&A. A limited set of "authentication plugins" should be available out of the box.

> command line switch for `--enable-authentication` (no need for `MODE` I think)

The concept of `MODE` was in line with a standardization of the out of the box authentication capabilities. It would also encourage a disciplined, modular, and hopefully extensible, approach to doing so. Then things like this will have a reference starting point for those that need to extend the authentication options beyond the out of the box shipped modes.

> Here's a minimal example of how that would look (tested, it works):
> 
> ```ruby
>   class Auth
>     def initialize(app)
>       @app = app
>     end
>     
>     def call(env)
>       if env['HTTP_GIT_AUTHOR_NAME'] && env['HTTP_GIT_AUTHOR_EMAIL']
>         env['rack.session'] = {} unless env['rack.session']
>         env['rack.session']['gollum.author'] = {
>           name:  env['HTTP_GIT_AUTHOR_NAME']
>           email: env['HTTP_GIT_AUTHOR_EMAIL']
>         }
>       end
>       @app.call(env)
>     end
>   end
> ```
> 
> and then:
> 
> ```ruby
>   class App < Sinatra::Base
>     use Auth # possibly conditional, use Auth if ... ?
>     ...
> ```
> 
> This could easily be expanded so as to make the exact conditions under which to set the session variables (e.g. the name of the http headers) dynamic.

I am a big fan of doing things the right way or by convention. Without extensive formal documentation (showing the right ways) or examples (establishing convention) to reference - the new implementations will not comply.

I am willing to put in the effort to learn and and make the patch, where it accomplishes al of the principles above. It will be a slow and steep learning curve.

**Comment by dometto** [comment]
>  A limited set of "authentication plugins" should be available out of the box.

Just to make sure you are aware, there is https://github.com/arr2036/omnigollum (also [Docker images](https://hub.docker.com/r/hotmaps/gollum) including omnigollum). I understand that many not cover all your requirements -- although it would be interesting to know why not.

**Comment by pdinc-oss** [comment]
> there is https://github.com/arr2036/omnigollum (also [Docker images](https://hub.docker.com/r/hotmaps/gollum) including omnigollum). I understand that many not cover all your requirements -- although it would be interesting to know why not.

Do you know when is it targeted for merging into mainline gollum?

**Comment by bartkamphorst** [comment]
> Do you know when is it targeted for merging into mainline gollum?

There are no plans to merge these two projects at this time.

**Comment by dometto** [comment]
Closing this for now. Proposals for adding omnigollum/auth to the Docker image (or providing support for one) should be discussed at https://github.com/gollum/docker or at https://github.com/arr2036/omnigollum

**Comment by pdinc-oss** [comment]
> Closing this for now. Proposals for adding omnigollum/auth to the Docker image (or providing support for one) should be discussed at https://github.com/gollum/docker or at https://github.com/arr2036/omnigollum

This pull request **_is not_** about merging the two projects. Please re-open with constructive requests for change.

**Comment by dometto** [comment]
@pdinc-oss sorry for the confusion. I was thinking: omnigollum implements everything you need (in effect, omnigollum just *is* the middleware-based approach I set out in the comments above). If there is a feature you are missing, could you please explain what it is and its use case? Thanks!

**Pull request closed without merging**
