### PR TITLE
Fix Windows assets and tests

### PR DESCRIPTION
**Pull request by dometto**
Was suffering from some branch pollution (of the example repo's), so better to start with a new branch.

### CODE REVIEW

**Comment by dometto** [comment]
```
81 tests, 244 assertions, 2 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
```

~Failure: test_guard_against_uploading_an_existing_file(Frontend)~ (currently failing on all platforms)

## UTF-8

`Failure: test_UTF_8_headers_href_preserved(Frontend)`: 

```
 </<h2 class="editable"><a class="anchor" (href|id)="(#)?\u1112\u1161\u11AB\u1100\u1173\u11AF" (href|id)="(#)?\u1112\u1161\u11AB\u1100\u1173\u11AF"><\/a>\u1112\u1161\u11AB\u1100\u1173\u11AF<\/h2>/> 

was expected to be =~

```
Relevant bit of the actual output: ` <h2 class=\"editable\"><a class=\"anchor\" href=\"#??????\" id=\"??????\"></a>\u1112\u1161\u11AB\u1100\u1173\u11AF</h2>\n" +"\r\n" +`

## Emojis

These tests are failing in gollum-lib, too, and should be solved there:

`Error: test_existing_emoji(Frontend_with_lotr): Encoding::UndefinedConversionError: "\x8F" to UTF-8 in conversion from Windows-1252 to UTF-8`
`Error: test_missing_emoji(Frontend_with_lotr):` same error as above

**Comment by bartkamphorst** [comment]
Getting pretty close! 👍

**Comment by dometto** [comment]
Using the gollum-lib `windows` branch and with [this fix](https://github.com/bonusly/gemojione/pull/68) for gemojione, I am now getting 0 failures 0 errors on Windows! 👍

**Comment by bartkamphorst** [comment]
Excellent news, thanks for tracking down all these issues!

**Pull request merged**
