### PR TITLE
Move primer to yarn

### PR DESCRIPTION
**Pull request by dometto**
Update primer to the latest version (20.8.0) via yarn.

### CODE REVIEW

**Comment by bartkamphorst** [comment]
Yikes!

**Comment by bartkamphorst** [comment]
Could we separate the move to yarn from the update to the latest version?

**Comment by dometto** [comment]
> Could we separate the move to yarn from the update to the latest version?

We can if the move to yarn is independently useful!

**Comment by dometto** [comment]
A list of all the breaking changes in the primer releases between the latest and the current version that we're using (15.2):

# 20.0.0
## Major Changes

* Comment box upload focus border-radius
* Global CSS focus styles
* Marketing: Remove unused pullquote selector
* UnderlineNav :focus styles Refactor selected state and spacing Add selected bold state override from github/github
* UnderlineNav bug fix
* Global focus style CSS from feature flag (next major)

# 19.0.0
## Major Changes

* Update marketing buttons (including color mode support)

# 18.0.0
## Major Changes

* Removing the rem() mixin and usages. Placing the computed values in place.
* Update v1 deprecations
* Rename modes.scss file to color-modes.scss and move from the base/ folder to the support/variables folder.
* Moving color modes to their own bundle, ./color-modes/ and separates color mode themes into their own scss file.
* Remove V1 color utilities
* Removing <kbd> import from markdown package. Going forward you'll need to include @primer/css/base/kbd.scss directly.
* Update utilities
*Remove break-word from utilities

# 17.0.0

## Major Changes

*  Replace border-overlay with border-primary
*  Marketing: Deprecate bg-shade-gradient
*  Add new marketing type scale
*  Marketing: Removing Inter font files and folder
*  Changeset change supported browsers.
*  Remove redundant marketing layout selectors
*  Marketing: use size modifiers that don't look like breakpoints modifiers
*  Update marketing button styles
*  Remove dependency on primer/octicons and force overflow visible
*  Merge overlapping marketing spacing utilities into primer core

# 16.0.0

## Breaking Change

* Update to Primer Primitives 4.0.0 primer/primitives#43
* Add color modes #1131

**Comment by dometto** [comment]
And using [this simple script](https://gist.github.com/kdzwinel/426a0f76f113643fa285) to find used CSS classes that are undefined, I get the following hits on the Home page:

```
0: "ff"
​
1: "page"
​
2: "minibutton-rename-page"
​
3: "minibutton-edit-page"
​
4: "search-form"
​
5: "minibutton-new-page"
​
6: "header-title"
​
7: "has-header"
​
8: "has-footer"
​
9: "has-sidebar"
​
10: "has-rightbar"
​
11: "gollum-textile-content"
​
12: "gollum-markdown-content"
​
13: "main-content"
​
14: "gollum-error"
​
15: "Box-condensed"
​
16: "dotted-spinner"
​
17: "hidden"
```

Not all of those look like they have anything to do with primer, but some of them do (e.g. `Box-condensed`).

Some more on the edit page:

```
0: "ff"
​
1: "edit"
​
2: "search-form"
​
3: "header-title"
​
4: "tabnav-div"
​
5: "tex2jax_ignore"
​
6: "active"
​
7: "function-button"
​
8: "octicon-bold"
​
9: "octicon-italic"
​
10: "octicon-code"
​
11: "octicon-list-unordered"
​
12: "octicon-list-ordered"
​
13: "octicon-quote"
​
14: "octicon-horizontal-rule"
​
15: "octicon-image"
​
16: "octicon-arrow-both"
​
17: "octicon-question"
​
18: "primary"
​
19: "ace_print-margin-layer"
​
20: "ace_1"
​
21: "expand-trigger"
​
22: "dotted-spinner"
​
23: "collapsed"
​
24: "collapsable"
​
25: "octicon-triangle-down"
​
26: "octicon-triangle-up"
​
27: "singleline"
​
28: "jaws"
​
29: "ph"
```

**Comment by bartkamphorst** [comment]
I'm not so sure your script is working correctly. Just from the top of my head I remember seeing styling for "dotted-spinner", "collapsed", "singleline", "jaws", "ph".

**Comment by bartkamphorst** [comment]
I was wondering whether you could embed the [view components](https://primer.style/view-components/) in this PR as well?

**Comment by dometto** [comment]
If I understand correctly, the view components needed by the `core` and `product` components are required automatically by the latter. Additional components that we want to use we could require separately. Are there any ones you are thinking apart from the dialog view component?

**Comment by bartkamphorst** [comment]
#1915 has been merged into master. If you could rebase this PR we can move forward with further styling / cleanup based on the latest version of Primer CSS and view components.

**Comment by dometto** [comment]
Rebased! Everything seems to be working well. I see CSS for "Box-overlay" and primer spinners inside the compiled `app.css`, so I think we have the components we want, too. If we need to separately load more components, we can always add that in a next PR.

**Comment by benjaminwil** [comment]
Very exciting!

**Review by bartkamphorst — APPROVED** [review]
Looks good to me!

**Pull request merged**
