### PR TITLE
Update sinatra and other dependencies. Closes #1193

### LINKED ISSUE #1193: Rails 5 compatibility
I can't upgrade do Rails 5, getting the following after `bundle update`:

```bash
Resolving dependencies....
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
      actionpack (= 5.0.0.1) was resolved to 5.0.0.1, which depends on
        rack (~> 2.0)

    gollum (~> 4.0) was resolved to 4.0.0, which depends on
      sinatra (>= 1.4.4, ~> 1.4) was resolved to 1.4.4, which depends on
        rack (~> 1.4)
```

Is there any work to make it compatible with `rack (~> 2.0)`?

### PR DESCRIPTION
**Pull request by dometto**
Had to replace the multiline regexps in `app.rb` with single line variants to get this to work with `sinatra v.2`. Also had to explicitly disable warnings in the test suite because `rake >= 11` throws *a lot* of warnings.

### CODE REVIEW

**Comment by dometto** [comment]
`sinatra v.2` depends on the `mustermann` gem, which requires MRI `>= 2.2.0`. Do we want to drop support for older rubies, or go along with the `sinatra` folks? The latter is important in so far `sinatra v1.4` depends on a fairly outdated `rack`.

**Comment by dometto** [comment]
And `rack` itself apparently also requires MRI `>= 2.2.2`.

**Comment by bartkamphorst** [comment]
Fine to drop older rubies for `5.x`.

**Comment by dometto** [comment]
@bartkamphorst did you already update `sinatra`, or was that just locally?

**Comment by bartkamphorst** [comment]
I did so on the `5.x` branch (here: https://github.com/gollum/gollum/commit/b47db5611b8db1bcf761f5e95f01d371f8740657).

**Pull request closed without merging**
