### PR TITLE
Added init script for Debian's SysV-style init system

### PR DESCRIPTION
**Pull request by n-st**
Adapted from the OpenRC init script in contrib/openrc/init.d/gollum.

### CODE REVIEW

**Comment by SkyCrawl** [comment]
Hello @n-st 

I'm not a maintainer but before this PR is merged, would you also consider adding a few words about this script (very very basic explanation and usage, perhaps) to the [appropriate wiki page](https://github.com/gollum/gollum/wiki/Gollum-as-a-service)? :)

**Comment by dometto** [comment]
Thanks for this @n-st! Would be great to have some docs in the wiki indeed.

**Comment by n-st** [comment]
I've added a short paragraph to the wiki: https://github.com/gollum/gollum/wiki/Gollum-as-a-service/d4b7b83e956397ee3750022b93267527891ee12f

The link to the script currently points to my fork of the gollum repo and will have to be updated once this pull request has been merged.

**Comment by bartkamphorst** [comment]
I like it! :+1:

**Comment by dometto** [comment]
Thanks again!

**Comment by n-st** [comment]
Glad to help.
I've also updated the link in the wiki to point to the official gollum repo instead of my fork.

**Pull request merged**
