### PR TITLE
Add mobile navigation menu

### PR DESCRIPTION
**Pull request by benjaminwil**
These commits add a navigation menu that is more suitable on narrow screens. I was able to utilize utilities provided by Primer CSS for all of this work.

While I was editing the nav bar-related templates, I also took the liberty to change the desktop navigation menu to use "button groups" for related buttons. While this is a minor user experience change, I think it's valuable to separate and group buttons based on the action. (Global wiki actions, current page actions, or page creation actions.)

Desktop menu:

Screenshot from 2021-02-13 17-58-07

Small- to medium-sized screens:

Screenshot from 2021-02-13 17-58-38

Very small screens:

Screenshot from 2021-02-13 18-16-10

### CODE REVIEW

**Comment by bartkamphorst** [comment]
Related to these buttons is [this discussion](https://github.com/gollum/gollum/issues/1591). Any thoughts about the naming of the buttons @benjaminwil ?

**Comment by dometto** [comment]
Mobile menu looks great!

**Comment by dometto** [comment]
I'm happy to merge this unless @bartkamphorst has any questions? The new button labels can be a separate PR, I suppose

**Comment by benjaminwil** [comment]
If you all have no preference, I would prefer to submit the button label changes as a separate PR.

**Comment by bartkamphorst** [comment]
Works for me!

**Pull request merged**
