### PR TITLE
Improve editor "Help" functionality

### LINKED ISSUE #1775: Dead link in the help panel to EmojiOne demo
**Describe the bug**
There is a dead link in the Help panel--the link to the EmojiOne demo does not work anymore: http://emojione.com/demo/

**To Reproduce**
1. Go to edit mode
2. Click on the "?" to open the help panel
3. Click on "Miscellaneous" on the left
4. Click on Emoji
5. Click on the link to the EmojiOne demo

### PR DESCRIPTION
**Pull request by benjaminwil**
This pull request resolves #1775. While resolving this issue, I saw other ways I could start improving the editor's function bar:

- I added Capybara tests.
- I made the "Help" button more accessible to screenreaders.

As Capybara was only just added to this project, I needed to add some convenience scaffolding so it'd work with my local environment.

### CODE REVIEW

**Comment by dometto** [comment]
Thanks! Looks good to me, not sure about the JRuby failure though.

**Comment by dometto** [comment]
Look like this test is a little flaky for some reason:

```
Default_keybindings#test_keybinding_unset [/home/runner/work/gollum/gollum/test/test_app.rb:1098]
Minitest::Assertion: Expected: true
  Actual: false
```

Restarting the jobs (on your other PR) fixed the test. Not sure if this is worth investigating :)

**Comment by benjaminwil** [comment]
Yes, I also attempted to rerun the CI jobs but I'm getting frequent failures. I'll investigate what's going on and put up another PR for it.

**Review by bartkamphorst — APPROVED** [review]

**Comment by dometto** [comment]
After https://github.com/gollum/gollum/commit/f5766c81e719da5679ed51a09416f6b53cf2fde9 this should be ready to go I think (after rebuilding the static assets)!

**Pull request merged**
