### PR TITLE
Docker support within the repository

### PR DESCRIPTION
**Pull request by darless1**
### Overview

- Adds a Dockerfile within this repository
- GitHub actions to build and test the image

### Why

This adds a Dockerfile within the repository, which in my experience, is standard practice. I am aware that there is a different repository already in place [gollum/docker](https://github.com/gollum/docker). From a testing and deployment point of view, the way that works is, it is already pulling a built Gollum package which does not tie into what we are trying to test with changes from this repository.

### Testing

This adds new GitHub Actions for building and testing the image. The workflow is called build-and-test. The build portion aims to use caching and docker buildx to use as much of the available cache as possible to speed up the build process. The test portion will run a rake test against the built docker image.

### Difference from gollum/docker [Dockerfile](https://github.com/gollum/docker/blob/master/Dockerfile)

- In the docker file, the gem `therubyracer` is installed. However, in my build and run, I did not see why this was necessary.
  - Not necessary from discussions in this PR
- Gollum is not installed, as I want to ensure it is built from what is in the repository.
- Always using ruby:2.7. With docker, we just need to pick one version that is the best to use. 

### Latest Run

Build & Push Result: https://github.com/darless1/gollum/actions/runs/937972913

### What else to get done?

- [x] Add an additional workflow to push to the latest tag whenever a push to the master branch is done. This would provide the absolute latest image to users as soon as pull requests have been completed.
  - [x] An administrator must add `DOCKER_HUB_USERNAME` to our GitHub Actions secrets.
  - [x] An administrator must add `DOCKER_HUB_ACCESS_TOKEN` to our GitHub Actions secrets.
- [x] README updates for Docker
  - No changes necessary, already points to wiki
- [x] Wiki updates for docker - mention that it is pending while this PR is Open
  - Mentioned in comment within the PR. All references to gollum/docker would need to be removed post PR change.

### CODE REVIEW

**Comment by benjaminwil** [comment]
I like this.

I am going to edit the PR description to add a couple additional to-do items:

- An administrator must add `DOCKER_HUB_USERNAME` to our GitHub Actions secrets.
- An administrator must add `DOCKER_HUB_ACCESS_TOKEN` to our GitHub Actions secrets.

The administrator must also have access to the Gollum Docker Hub account, which I don't.

**Comment by darless1** [comment]
@benjaminwil you have any idea what the rubyracer is for? 

Also should the docker image have all the gems to support all the formats? Ex asciidoc, etc. currently a lot of them are grayed out.

**Comment by benjaminwil** [comment]
`therubyracer` as part of the Docker container has been discussed a bit here: https://github.com/gollum/docker/issues/2

It is for compiling JavaScript assets.

I am pretty sure we would not need this in the Docker image for the following reasons:

- When you `gem install gollum` all of the assets come precompiled. Users do not need to compile SCSS or JavaScript before running the server.
- In my experience `therubyracer` is something you'd installed on Windows or macOS if your development environment doesn't have another way to compile Javascript (like `nodejs`). On Linux (or in a Docker container) you might as well just installed `node` instead.
- The Docker container won't use JRuby, so we don't need a `therubyrhino` compatible asset compiler like `therubyracer`.

It is possible I am missing something, or that I am misinformed. But I feel kind of confident we don't need `therubyracer` here.

**Comment by benjaminwil** [comment]
> Also should the docker image have all the gems to support all the formats? Ex asciidoc, etc. currently a lot of them are grayed out.

Perhaps we should just start by getting the Docker container to parity with `gollum/docker`.

Maybe in the future we can devise a way to let end users configure optional dependencies via a script and their `configuration.rb` file.

**Comment by darless1** [comment]
@dometto - Do you know who the admin is of https://hub.docker.com/u/gollumorg? They will need to do 2 of the tasks here that @benjaminwil  added. Setting up the repository secrets:
- secrets.DOCKER_HUB_USERNAME
- secrets.DOCKER_HUB_ACCESS_TOKEN

**Comment by darless1** [comment]
@benjaminwil I noticed that while github actions are running, they are not set up as an check on the repo like travis was. Can this be done?

**Comment by darless1** [comment]
As far as the README, it already points to the wiki. And in the wiki, most of it can remain the same I think.

The only statement once this is merged would be to update the wiki:

https://github.com/gollum/gollum/wiki/Gollum-via-Docker#official-docker-image-at-docker-hub
```
Official Docker image at Docker Hub
An official image is being built at gollumorg/gollum. It is linked to the following official repo: https://github.com/gollum/docker

You can run it with:

docker run -v $(pwd):/wiki -p 4567:4567 gollumorg/gollum
```

To not mention gollum/docker, just state that it is part of the main gollum/gollum repository.

**Comment by darless1** [comment]
Changes from the latest commit:
- Include other markup files which do not seem to add much to the docker file.
- Added dockerignore which lowered the compressed size in dockerhub
- Modified gollum start up for docker to always run with mathjax

At this point, please let me know if anything further is needed for this PR.

**Comment by dometto** [comment]
The admin for the `gollumorg` docker repo is @scolytus. @scolytus it seems like you're too busy to maintain the gollum `Docker` image, No problem -- we all know how tough it can be to make time for open source work! Would you mind handing over or sharing the responsibility with @darless1 (assuming he's interested), perhaps?

**Comment by darless1** [comment]
@dometto I think the members of this repo need to have access to Dockerhub, this way there is no dependency of waiting for functionality on another user. One of the members could always create a dockerhub account for gollum and add gollum there so it is something like gollum/gollum. I'm more than happy to contribute, but I do not have the time commitment to be a member at the moment.

**Comment by darless1** [comment]
@dometto , @benjaminwil - Looks like no recent updates. If the two of you want to make me a member, I'll gladly create a gollum/gollum in dockerhub and update the settings in github to have the proper settings set up. I'll also add both of you as members of dockerhub. I'd like to see this move along, it will definitely make development easier to test out different packages as needed.

**Comment by dometto** [comment]
Ah, `gollum/gollum` now looks available on `Dockerhub`. I thought @scolytus originally went for `gollumorg` because someone had taken `gollum`. I've just looked and annoyingly can't read the access keys for `gollumorg` from GitHub secrets. So our choices are:

- either @scolytus adds us as admins to `Dockerhub` and we continue using `gollumorg`
- or we just start a new org named `gollum` on `Dockerhub`

Ping @scolytus again :)

**Comment by darless1** [comment]
@dometto I would prefer the latter due to inactivity from @scolytus. Looking at @scolytus I see his last contribution on Github from Sept 2020, so it is unlikely we will get a response any time soon. Please go ahead and set up Gollum on Dockerhub and let me know when that's done.

**Comment by dometto** [comment]
It looks like a `gollum` org already exists on Dockerhub (even though I can't find it). I'll try to contact @scolytus by email, since it would be a bit unfortunate to proliferate orgs with names like `gollum` unless necessary. Any suggestions for alternative org names welcome.

**Comment by darless1** [comment]
Good luck with the communication. Until then this PR exists for anyone that needs an up-to-date Dockerfile or if they want to build it themselves. 

@dometto  The other option is for me to switch from Dockerhub to using Gihub's registry for testing and publishing. Let me know if I should switch to using that instead, then we don't have to wait for Dockerhub and keep it all in GitHub. It's not ideal since Dockerhub is the main use case, but maybe useful for now until Dockerhub access can be acquired.

**Comment by darless1** [comment]
@dometto  any luck? It's been 8 days.
Perhaps we should switch to the GitHub registry for the time being if the decision is to wait until @scolytus responds?

**Comment by dometto** [comment]
@darless1 no luck unfortunately. Is there another sane org name we could come up with for Dockerhub? I can also try emailing Dockerhub and ask them about the availability of `gollum`, as I can't seem to find an actual project by that name.

**Comment by darless1** [comment]
@dometto Honestly, I don't think it matters short term what it is called, just have it be named something associated with gollum,

I created gollumwiki which I think is a sane name and it is available. Let me know if that works and how you would like me to add your email address to it so that you and your team have admin permissions.

**Comment by embolon** [comment]
Just found out the docker file will be merge back to the main repo. Is it possible to build the new docker image for arm/arm64 arch as well?

**Comment by darless1** [comment]
Docker ARM support.
Is it possible to build for additional arch - yes. However, I would say that it should be done separately from this pull request, as it will slow down workflows (building 3 arch instead of 1). I did a test where the amd64 workflow to build and test took slightly less than 2 minutes, vs the arm64 and arm took more than 30 minutes each.

Additionally, when this is merged in, I could look at updating the functionality to build the additional arch, perhaps during deployment and not the main build process. The last point, with the Dockerfile being up to date, any user can build for the system they plan to run it on.

**Comment by darless1** [comment]
Rebased against master to pull in the latest changes from the repository.

**Comment by Tony2** [comment]
I like this, seems more polished and better maintained than the official docker support by gollum.

**Comment by dometto** [comment]
@darless1 I've added the Docker credentials to this repo's secrets, but login is still failing. Perhaps the current setup still assumes the wrong name for the Dockerhub repo?

**Comment by darless1** [comment]
@dometto The credentials should look like:
DOCKER_HUB_USERNAME: gollumwiki
DOCKER_HUB_ACCESS_TOKEN: The token created.

When

**Comment by darless1** [comment]
FYI: Closed the merge request by mistake, reopened it right away.

**Comment by darless1** [comment]
@dometto I made the following changes with my recent commit:

- Docker test portion does not push up to docker, the login is only to ensure that secrets are set correctly.
- Docker deploy during a push action to the master branch is done only if the push is to `refs/heads/master`

The failure currently, looks like that this repository does not have the secrets set. You can see that  in the error that the action shows:
Error: Username and password required
test_login

Make sure the secrets in the setting use the following names:
secrets


I tested this myself in my fork since I have access to gollumwiki with my user and all worked. You'll see the results from the screenshot below.
gollumwiki

actions

**Comment by dometto** [comment]
The secrets are set for this repository, but I think what's causing the trouble is this disclaimer I just saw on the "secrets" page:

> Secrets are not passed to workflows that are triggered by a pull request from a fork.

So maybe it does not make sense to run the Docker workflow on pull request at all, and just on push to `master`?

**Comment by darless1** [comment]
@dometto  I removed the docker login from the docker test workflow, leaving it in place for the docker deployment workflow.

**Comment by dometto** [comment]
Thanks @darless1! Now let's see how it goes [here](https://github.com/gollum/gollum/runs/3229998011)...

**Comment by darless1** [comment]
Looks like it worked well.

**Pull request merged**
