### PR TITLE
[feature] verbose search

### PR DESCRIPTION
**Pull request by C-Abner**
modify something for "verbose search" feature.

just like 
image

also modify some files on gollum,  gollum-lib and gollum-grit_adapter.

### CODE REVIEW

**Comment by dplanella** [comment]
Thanks for working on this, it looks like a great addition. It might be worth mentioning this on the initial comment on the pull request, but as a note for testers, these additional changes are also needed:

- On gollum-lib:
  - https://github.com/C-Abner/gollum-lib/commit/228b465d32c73885c71c9c17a2adef0f4e5ee415
- On grit_adapter:
  - https://github.com/C-Abner/grit_adapter/commit/7d1cfa2a2aad5ba4d981d84b682a5b9b93ef5825
  - https://github.com/C-Abner/grit_adapter/commit/b38bd9e84584a3e7143f685ffaaa9e1f90ad80a1

Also, while we're at it, a nice addition would be for each result to return its readable title (e.g. h1) or default to displaying the repo path (current behaviour). That'd make the results page much friendlier to read.

**Comment by dometto** [comment]
Thanks for working on this! :+1: And sorry for the slow response. To get this merged, could you please:
* open PRs for the other gems/projects that @dplanella mentions
* change the target for this PR to the `5.x` branch
* add a test for the new behavior

Also, we should make sure that the other adapters (`rugged` and `rjgit`) support the new behavior, or that this defaults to something sane in case the adapter doesn't return the new verbose information.

**Comment by dometto** [comment]
Ping @C-Abner

**Comment by bartkamphorst** [comment]
Notice that the Rugged adapter and the RJGit adapter also would need to implement a `verbose_grep` method for this to work uniformly across adapters.

**Comment by dometto** [comment]
Ping @C-Abner. Could you reopen this PR against the `5.x` branch, or let us know if it's alright for us to create a new PR based on your code?

**Comment by dometto** [comment]
Working on verbose search [here](https://github.com/gollum/gollum-lib/pull/343). When it is merged, the frontend will have to be changed accordingly, but the API differs from the one that @C-Abner assumes in this PR. So closing this, will implement changes to the search view in a new PR soon.

**Pull request closed without merging**
