### PR TITLE
raspberry pi compatibility

### PR DESCRIPTION
**Pull request by cooperspencer**
I added platforms to the `build and push` task and added libc6-compat to the docker container.

### CODE REVIEW

**Review by benjaminwil — APPROVED** [review]

**Comment by benjaminwil** [comment]
Thank you!

**Comment by dometto** [comment]
Sadly it looks like that the Docker Deploy action is failing. The nokogiri build (as part of the `bundle install` step) is failing on `arm`: https://github.com/gollum/gollum/runs/6248371141?check_suite_focus=true

@cooperspencer have you successfully built gollum/nokogiri on `arm` locally? If you have no idea what's causing this, I can investigate myself. :)

**Comment by cooperspencer** [comment]
@dometto I just rebuild the docker container on my pi and it runs fine. So I am a bit clueless right now tbh...

**Comment by benjaminwil** [comment]
I noticed this earlier and was planning to try doing a manual build myself. If I can't get it working I might revert this PR.

**Comment by benjaminwil** [comment]
I was also able to build the container successfully for platform `linux/arm64`, which makes me think there is a package missing from the GitHub Actions environment. I'm just not sure how to identify what package that might be?

**Comment by cooperspencer** [comment]
If I read the error message correct, the problem is with arm/v6 and v7. If we remove those architectures from the pipelines it should be fine.

**Comment by benjaminwil** [comment]
Thank you!

**Pull request merged**
