### PR TITLE
Introduce directory permission check to docker-run.sh script (#2084)

### PR DESCRIPTION
**Pull request by Hooverdan96**
1. Please clearly explain the purpose of your PR. Let us know if it introduces a new feature, an enhancement, or fixes a bug.
Enhancement Proposal:
For docker images starting with 6.0 a non-root user needs the correct permissions to the mapped host volume:
`-v /path/to/git/directory/on/host:wiki`. If these are not set correctly, the docker container will continue to run, but the web page will not work.
This introduces a short check at the beginning of docker-run.sh to check for existence and writeability of the volume. If true, continue with the script, if false, exit. For both conditions issue a message describing success or failure.

2. Please link any issues that your PR addresses.
Inspired by #2084

3. If your PR changes any of the CSS or JavaScript under `lib/gollum/public`, don't forget to update the static asssets as explained [here](https://github.com/gollum/gollum/blob/master/CONTRIBUTING.md#updating-static-assets).
No changes to CSS/JavaScript

Added to [LATEST_CHANGES.md](https://github.com/gollum/gollum/blob/master/LATEST_CHANGES.md)

### CODE REVIEW

**Comment by dometto** [comment]
Thanks for helping out with this!

I'm wondering if actually exiting is too drastic a measure when the directory is not writable, since Gollum also has a read-only mode. Just throwing the error message will be a huge help to users (and to us, if people do file bug reports).

**Comment by Hooverdan96** [comment]
yes, that makes sense. I will adjust it so it will just throw the message and then continue.

**Comment by dometto** [comment]
Thanks @Hooverdan96!

**Comment by benjaminwil** [comment]
Awesome! Thank you @Hooverdan96 💯

**Pull request merged**
