### PR TITLE
Fix absense of visual feedback when uploading with drag-and-drop

### PR DESCRIPTION
**Pull request by ProgramFan**
Address #1327

### CODE REVIEW

**Comment by ProgramFan** [comment]
I would prefer a separate entry as they serve different purposes like that of `#gollum-editor-body`.

No spinner at the moment. ACE editor takes over the place of the original editor body and where shall we display the spinner? I failed to find the spinner in the CSS. 😢

**Comment by ProgramFan** [comment]
All the concerns are addressed in the latest commit. The spinner is now shown when uploading and the CSS is cleaned up.

**Comment by dometto** [comment]
Great!

**Comment by bartkamphorst** [comment]
Works like a charm. Thanks for resolving this, @ProgramFan !

**Pull request merged**
