### PR TITLE
Improve presentation of page navigation and `#head` area on mobile devices

### PR DESCRIPTION
**Pull request by benjaminwil**
I noticed that the `div#head` header area of many pages was large and untenable on mobile devices, especially if, for example, the page being edited has a title of more than a couple of words long. My solution to this was to reduce the size of the navigation menu and `#head` header title text so it fits better on the screen.

I have more detailed rationale for my changes in each commit message.

Before:
Screen Shot 2021-08-22 at 16 05 45

After:
Screen Shot 2021-08-22 at 16 03 35

### CODE REVIEW

**Review by dometto — APPROVED** [review]
Looks good to me!

**Review by bartkamphorst — APPROVED** [review]
PR looks good. I'm just not getting your note "that while the `h1` inside of `#wiki-content` has been given the new `.header-title` class, I'm not actually re-styling this
`h1` like the other ones. (Although it, too, is now centered on mobile.)". Which other ones are you referring to here?

**Comment by benjaminwil** [comment]
@bartkamphorst 

In `lib/gollum/templates/wiki_content.mustache`, the `.header-title` is not a `#head .header-title`, so it doesn't inherit the new styles.

But I've added a `center` style.

Maybe the comment I made is too complicated. I will go back and fix it.

**Comment by dometto** [comment]
Is this ready to merge now?

**Comment by benjaminwil** [comment]
Sorry. I’ve been on vacation. I will fix the commit message, rebase, and merge this tomorrow.

**Comment by dometto** [comment]
No worries of course! Thanks and hope you had a good time. :)

**Comment by benjaminwil** [comment]
This is ready to merge. I didn’t merge yet due to unrelated CI failures.

**Pull request merged**
