### PR TITLE
Primer CSS breadcrumbs (related to #1394).

### PR DESCRIPTION
**Pull request by bartkamphorst**
Screen Shot 2020-03-25 at 18 20 13
Screen Shot 2020-03-25 at 18 19 15

### CODE REVIEW

**Comment by dometto** [comment]
Looks great!

**Comment by bartkamphorst** [comment]
Thanks! Hold on while I try to fix the errors.

**Comment by dometto** [comment]
From Travis:

```
<"<a href=\"/gollum/overview\">Home</a> / <a href=\"/gollum/overview/Mordor/\">Mordor</a> / <a href=\"/gollum/overview/Mordor/Eye-Of-Sauron/\">Eye-Of-Sauron</a> / Saruman"> expected but was

<"<nav aria-label=\"Breadcrumb\"><ol><li class=\"breadcrumb-item\"><a href=\"/gollum/overview\">Home</a></li>\n" +
```

Weird that new result doesn't include Mordor, Saruman, or Sauron?

**Comment by bartkamphorst** [comment]
> <"<nav aria-label=\"Breadcrumb\"><ol><li class=\"breadcrumb-item\"><a href=\"/gollum/overview\">Home</a></li>\n" +
> ```
> 
> Weird that new result doesn't include Mordor, Saruman, or Sauron?

Not really, notice the `+`. :) 

`"<nav aria-label=\"Breadcrumb\"><ol><li class=\"breadcrumb-item\"><a href=\"/gollum/overview\">Home</a></li>\n" +
"<li class=\"breadcrumb-item\"><a href=\"/gollum/overview/Mordor/\">Mordor</a></li>\n" +
"<li class=\"breadcrumb-item\"><a href=\"/gollum/overview/Mordor/Eye-Of-Sauron/\">Eye-Of-Sauron</a></li>\n" +
"<li class=\"breadcrumb-item\" aria-current=\"page\">Saruman</li>\n" +
"</ol></nav>">`

**Comment by bartkamphorst** [comment]
Feel free to merge if it looks okay to you @dometto .

**Pull request merged**
