### PR TITLE
Enables the option of having a template for new pages

### PR DESCRIPTION
**Pull request by brandubh**
if --template-page specified and /_Template page git committed, the raw content from _Template are used as default content for new pages.

### CODE REVIEW

**Comment by bartkamphorst** [comment]
I quite like this idea. What are your thoughts on this feature, @dometto @sunny ?
Code-wise this will need tests before it can be merged.

**Comment by dometto** [comment]
:+1: It needs tests, and some logic in case `_Template` does not exist.

**Comment by brandubh** [comment]
thx guys, going to add some error management logic and tests, just be patient first lines of Ruby ever :-)

**Comment by dometto** [comment]
Looks good to me now, @brandubh! Sorry for the slow response. However, perhaps it would be best to merge this new feature into the `5.x` branch. Could you perhaps reopen the PR against that branch? Thanks!

**Comment by brandubh** [comment]
Moved to 5.x

**Pull request closed without merging**
