### PR TITLE
Update Mermaid to 11.4

### PR DESCRIPTION
**Pull request by benjaminwil**
This pull request replaces #2077.

The original pull request is good, but it's difficult to verify the authenticity of precompiled assets.

This pull request verifies them by:

1. Re-running Yarn install: `yarn install --check-files`
2. Removing all assets and rebuilding them: `rm -rf lib/gollum/public/assets/* && bundle exec rake precompile`

### CODE REVIEW

**Comment by benjaminwil** [comment]
@linster I also adjusted the `LATEST_CHANGES.md` because we've actually upgraded to Mermaid 11.4. (`^11.1`)

**Comment by benjaminwil** [comment]
Not sure why, but the Docker build step is now failing.

**Comment by bartkamphorst** [comment]
Fair enough. I second the idea that the major changes in mermaid warrants a minor-level release.

**Comment by benjaminwil** [comment]
There are integration tests that indicate that Mermaid is still working, but I also manually tested a document with a Mermaid diagram to be sure. 👍

**Pull request merged**
