### PR TITLE
feature / 629 breadcrumbs

### PR DESCRIPTION
**Pull request by aspyct**
Proposal to fix issue #629 

It adds a breadcrumb, based on the one from "all pages", to every wiki document. I'm not too fan of the css styling I've made, but I'm unsure how we'd like the breadcrumbs to look like. Suggestions are welcome!

I'm not a ruby developer, so you may want to double check the implementation. Also, I could not find how to run the tests. Apparently my rake version is out of date, but it's the system rake, so I'm afraid of breaking stuff if I change it.

### CODE REVIEW

**Comment by dometto** [comment]
Closing this until we have more of an idea where to go with CSS/SASS.

**Comment by bartkamphorst** [comment]
Not sure I agree. Closing this will likely take it off our radar. I agree that we want to settle on appropriate styling first before merging, but I propose to keep it open until we settle on that. I quite like breadcrumbs.

**Comment by sunny** [comment]
Styling is ok as-is for me! They could be improved but we can ship like this.

@aspyct: to run the tests without changing your system's `rake` I'd suggest installing a fresh Ruby version with something like rbenv.

Would you mind trying that and writing a test for the breadcrumb generator?

Having mutually exclusive options would fix the title issue as a start.

**Comment by dometto** [comment]
Fair enough. :)

**Comment by dometto** [comment]
@aspyct, re mutually exclusive h1-titles and breadcrumbs, yeah, that sounds great. Sorry for the long wait, I was trying to get some core and CSS rewriting in before coming back to this, but obviously that took way too long, and we shouldn't make this PR hang on that. Apologies.

**Comment by bartkamphorst** [comment]
@aspyct Any chance you'd be willing to extend this PR with @sunny 's proposed changes? I'd really like to include your work in a next release.

**Comment by aspyct** [comment]
Hi @bartkamphorst 

Unfortunately I'm schedule-stressed right now until end of December, and will be on a long trip abroad after that without my computer. I won't have time to do as requested.

**Comment by bartkamphorst** [comment]
Understandable! Thanks for the quick response, and of course for the work you put into this PR.

**Comment by PeteMichaud** [comment]
I see the unsuccessful merge attempt on this, but not movement on the feature since December of last year? Is this close, could someone without much context (like me) push it over the finish line?

**Comment by bartkamphorst** [comment]
@PeteMichaud I think so. 👍 These are the two main points left to be addressed:
* Writing tests for the breadcrumb generator;
* Proper styling when the `--h1-titles` option is used.

The comments to this issue will give you some relevant context about these two points, but feel free to ask for clarification!

**Comment by thomaskuntzz** [comment]
Hmmm... Could someone explain me how to get nested directories of pages in Gollum ? :sweat_smile: Right now I can't get anything but all the pages without any structure or nesting within directories...

**Comment by adamneilson** [comment]
Hi @thomaskuntzz, it's pretty simple. Just create a link which includes the structure you want like this:

```
Link to my [nested page](folder_a/folder_b/nested_page)
``` 

Save that, click the link and add some content to the nested page. When you save that it will be created within nested directories.

Hope that helps.

**Comment by thomaskuntzz** [comment]
Okay, thanks, that works!
I tried to add manually some articles in markdown and it didn't show up on the web interface because I didn't commit the added files into git. :slightly_smiling_face:

**Comment by dometto** [comment]
Good that you got this working. I'll close this PR since it's inactive, and we'll have a new chance to implement this with the upcoming fronted changes by @thomaskuntzz. :)

**Comment by bartkamphorst** [comment]
@PeteMichaud I know it's been a long time, but would you be interested in finishing up this PR (breadcrumb for gollum)?

**Comment by dometto** [comment]
Agreed!

**Pull request closed without merging**
