### PR TITLE
Update Mousetrap and use new 'mod' helper

### PR DESCRIPTION
**Pull request by thomaskuntzz**
Since version 1.4, a generic 'mod' helper can be used for cross
platform shortcuts. I updated Mousetrap to latest v1.6.1 and
used 'mod+s' instead of ['ctrl+s', 'command+s'] for the editor's
keyboard shortcut.

See https://craig.is/killing/mice#api.bind.combo

### CODE REVIEW

**Comment by thomaskuntzz** [comment]
Don't know if it's useful but still...

**Comment by dometto** [comment]
Seems like a good idea. Could you update the PR to target the `5.x` branch, though? @bartkamphorst can you explain the `jruby` failures on Travis?

**Comment by bartkamphorst** [comment]
On 7/31/17 5:29 PM, Dawa Ometto wrote:
> Seems like a good idea. Could you update the PR to target the |5.x|
> branch, though? @bartkamphorst <https://github.com/bartkamphorst> can
> you explain the |jruby| failures on Travis?

Looks like the wrong Java is being used (should be JDK 8 or higher).

**Comment by dometto** [comment]
Can't get Travis to respect the new jdk settings for this PR, but the jruby test should be gone when we merge this (right after @thomaskuntzz changes the target to `5.x`).

**Comment by thomaskuntzz** [comment]
I changed the target branch, but there are some conflicts. Doesn't seem to be very complicated but I'll let you resolve them as I'm not familiar with the code in question :wink:

**Comment by dometto** [comment]
👍

**Comment by dometto** [comment]
Merged! Many thanks.

**Comment by thomaskuntzz** [comment]
Wasn't anything remotely close to a substantial change... 😉

**Pull request merged**
