### PR TITLE
Support for emoji

### PR DESCRIPTION
**Pull request by svoop**
See #1125 for more.

### CODE REVIEW

**Comment by dometto** [comment]
Thanks for your work on this! Regarding the switch: in general I want to be careful in adding new switches, as I explained in https://github.com/gollum/gollum/issues/1127#issuecomment-210834450. But since emojis are popular these days, perhaps this merits a user-friendly switch. What do others think?

**Comment by svoop** [comment]
@dometto In case the switch question is blocking the merge: I don't mind removing it for the sake of not having too many switches. The `config.rb` is way more useful anyways :smile:

**Comment by bartkamphorst** [comment]
Can we use any of the existing EmojiOne gems so that we don't have to bundle the images with gollum? I'm worried about the maintenance of these images.

**Comment by svoop** [comment]
I've tried that at first but for some reason I don't remember had to drop it. I can take another look though.

**Comment by bartkamphorst** [comment]
That would be great. 👍

**Comment by svoop** [comment]
@bartkamphorst Here you go: The emoji are now served via their own route `/emoji/:name` which streams the PNG directly from the gem. 

By the way: Any particular reason why you have Travis test against `jruby-19mode`? I had to use a rather ugly workaround `"string".each_byte.to_a` for the Ruby 2 equivalent `"string".bytes` in one of my tests to pass in 1.9 mode.

**Comment by bartkamphorst** [comment]
> The emoji are now served via their own route /emoji/:name which streams the PNG directly from the gem.

Very cool. 👍 I'll try to find time soon to examine the code in detail.
 
> Any particular reason why you have Travis test against jruby-19mode? 

Yes, because when we added jruby it ran in 1.8.7 mode by default... I take it from your comment that that has changed. 😉

**Comment by bartkamphorst** [comment]
PR looks very clean to me. 👍 Okay to merge, @dometto?

**Pull request merged**
