### PR TITLE
Remove fileview from gollum and rely on /pages.

### PR DESCRIPTION
**Pull request by bartkamphorst**
@dometto Any comments?

### CODE REVIEW

**Comment by dometto** [comment]
👍 Do we want to remove whatever assets are specific to the fileview now or in a later PR?

**Comment by bartkamphorst** [comment]
Are you thinking of the images? Because I was thinking of reusing those for the pages view later on (the trashcan icon, etc.).

**Comment by dometto** [comment]
Good plan. I thought there might also be some specific CSS though, because of the non-standard look of the fileview. But I can't really locate any, except for the stuff to do with the icons.

**Comment by dometto** [comment]
Right! All ready then :)

**Pull request merged**
